// app/layout.tsx
import './globals.css';
import type { Metadata } from 'next';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import { Geist, Geist_Mono } from 'next/font/google';
import { Poppins } from 'next/font/google';

import ClientProviders from './ClientProviders';
// import AuthProvider from '@/Grocery/Authprovider'; 

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });
const poppins = Poppins({ variable: '--font-poppins', weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Grocery App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${geistMono.variable} ${geistSans.variable} antialiased`}>
        <ToastContainer theme="dark" />
        {/* <AuthProvider> */}
          <ClientProviders>
            {children}
          </ClientProviders>
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
